
-- 1. What are the names of all the countries in the country table?
SELECT country_name FROM country;

-- 2. What is the total number of customers in the customers table?
SELECT COUNT(customer_id) AS Total_Customers FROM customers;



-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
select AVG(age),can_email AS AVG_age from customers
WHERE can_email = 'yes';


-- 4. How many orders were made by customers aged 30 or older?

SELECT COUNT(order_id) AS 'orders made by customers age 30 or older' FROM customers c
JOIN Orders o ON c.customer_id=o.customer_id
WHERE age >= 30;

-- 5. What is the total revenue generated by each product category?

SELECT p.category,SUM(p.price) AS 'total revenue generated by each product' FROM products p
JOIN baskets b ON p.product_id=b.product_id
JOIN orders o ON b.order_id=o.order_id
GROUP BY p.category;


-- 6. What is the average price of products in the 'food' category?




SELECT category, AVG(price) AS 'avg price of food category'
FROM products
WHERE category = 'food'
GROUP BY category;


-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?


SELECT sales_channel, COUNT(order_id) AS 'total orders of each sales channel' FROM Orders
GROUP BY sales_channel;




-- 8.What is the date of the latest order made by a customer who can receive marketing emails?

SELECT c.customer_id,o.date_shop,c.can_email,
RANK()OVER(PARTITION BY C.customer_id ORDER BY o.date_shop DESC) AS rnk from customers c
JOIN orders o ON c.customer_id=o.customer_id
WHERE can_email = 'yes';

-- 9. What is the name of the country with the highest number of orders?

SELECT c.country_name,COUNT(o.country_id) AS 'country with the highest number of orders' FROM country c
JOIN orders o on c.country_id=o.country_id
GROUP BY c.country_name
ORDER BY 'country with the highest number of orders' DESC
LIMIT 1;



-- 10. What is the average age of customers who made orders in the 'vitamins' product category?




SELECT ROUND(AVG(c.age)) AS 'avg customer age' FROM customers c
JOIN orders o ON c.customer_id=o.customer_id
JOIN baskets b ON b.order_id=o.order_id
JOIN products p ON p.product_id=b.product_id
where p.category = 'Vitamins';





